AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'AWS RDS Postgres with PostGIS and Python Flask microservice using Auto Scaling'
Parameters:
  DBName:
    Default: MyDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
Resources:
  PostGreSQLDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref 'DBName'
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.small
      Engine: postgres
      EngineVersion: 10.5
      MasterUsername: !Ref 'DBUser'
      MasterUserPassword: !Ref 'DBPassword'
Outputs:
  ConnectionString:
    Description: JDBC connection string for the database
    Value: !Join [
      '',
      [
        'jdbc:postgres://',
        !GetAtt [PostGreSQLDB, Endpoint.Address],
        ':',
        !GetAtt [PostGreSQLDB, Endpoint.Port],
        /,
        !Ref 'DBName'
      ]
    ]
